export const FLOWER = [
  {
    plantName: "등심붓꽃",
    scientificName: "Sisyrinchium angustifolium Mill.",
    familyName: "붓꽃과 Iridaceae",
    nameOrigin: "",
    plantingLocation: "초본원",
    distribution: "제주도",
    floweringPeriod: "봄",
    height: "10-20cm",
    leafCharacteristics:
      "잎은 선형이고 폭2-3mm이며 가장자리에 작은 톱니가 있다. 경생엽 밑부분은 엽초로서 원줄기를 감싸고 양쪽 가장자리가 원줄기로 흐른다. 윗부분은 뾰족하고 녹색이며 가장자리에 잔톱니가 있다.",
    bloomingSeason: "5",
    bloomingDetails:
      "지름 1.5cm정도 되고 원줄기 끝에 달린 2개의 포 사이에서 2-5개의 꽃이 핀다. 소화경 밑에는 소포가 있고 화피는 밑부분이 짧은 통같으며 겉에 백색 선모가 있다. 열편은 5개이고 수평으로 퍼지며 도란상 긴 타원형으로 끝이 뾰족하다. 자주색 또는 백자색 바탕에 자주색 줄이 있고 밑부분이 황색이다. 수술은 3개, 암술은 1개, 자방은 하위이고 선모가 있다.",
    stemCharacteristics: "원줄기는 편평하고 녹색이며 좁은 날개가 있다.",
    hardiness: "",
    utilization: "관상용",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200000779.jpg",
    description: "여러해살이풀로 높이 20~30cm 자라요. 푸른 보라색 또는 하얀 보라색 꽃이 피어요.",
  },
  {
    plantName: "메꽃",
    scientificName: "Calystegia japonica (Thunb.) Chois.",
    familyName: "메꽃과 Convolvulaceae",
    nameOrigin: "",
    plantingLocation: "산림욕장",
    distribution: "제주도",
    floweringPeriod: "여름",
    height: "2m",
    leafCharacteristics:
      "잎은 호생하고 엽병이 길며 긴 타원상 피침형으로 밑부분이 이저이고 뾰족하며 길이가 5-10cm이고 폭은 옆으로 나온 돌기와 더불어 2-7cm이다.",
    bloomingSeason: "6",
    bloomingDetails:
      "연한 홍색 꽃이 엽액에 1개씩 달리며 화경이 길다. 꽃받침 밑에 있는 2개의 포는 녹색으로 난형이고 길이가 2-2.5cm이며 밑부분이 약간 심장형이고 꽃받침은 5갈래로 갈라져 있다. 화관은 길이가 5-6cm, 지름이 5cm이고 깔때기모양이며 수술은 5개가 있으며 암술은 1개가 있다.",
    stemCharacteristics: "",
    hardiness: "",
    utilization: "식용",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200001536.jpg",
    description: "덩굴성 여러해살이풀로 연한 홍색 꽃이 피어요. 잎은 어긋나고, 꽃은 잎겨드랑이에 1개씩 달려요.",
  },
  {
    plantName: "바위연꽃",
    scientificName: "Orostachys iwarenge (Mak.) Hara",
    familyName: "돌나물과 Crassulaceae",
    nameOrigin: "어릴 때 바위에 잎이 퍼져 붙은 상태가 연꽃 같아서 이정석 교수가 바위연꽃이라는 이름을 지었다.",
    plantingLocation: "온실",
    distribution: "제주도",
    floweringPeriod: "가을",
    height: "",
    leafCharacteristics:
      "잎은 총생한다. * 근생엽: 육질이고 편평하며 긴 타원상 주걱 모양으로 끝이 뭉뚝하거나 둥글다. 길이 3-7cm, 폭 7-28mm이며 백록색이다. * 경생엽: 호생한다.",
    bloomingSeason: "10",
    bloomingDetails:
      "화축은 직립하고 하단부에 잎이 밀생한다. 화수에는 매우 많은 꽃이 달리며 화축의 길이 5-20cm이다. 꽃은 흰색이고 꽃자루가 짧으며 꽃 밑에 2개의 작은 포가 달린다. 포는 난형으로 끝이 뾰족하다. 꽃잎의 길이 5-7mm이고 꽃받침 길이의 약 2배이며 피침형으로 끝이 뾰족하다. 꽃받침은 녹색이고 열편은 5개로 피침형이다. 수술은 10개이고 꽃밥은 담황색이다. 자방은 5개이고 암술대는 짧다.",
    stemCharacteristics: "",
    hardiness: "강함",
    utilization: "관상용",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200000936.01-51.jpg",
    description:
      "바위연꽃은 흰색 꽃이 피어요. 잎은 육질이며 긴 타원상 주걱 모양이에요. 화축은 직립하고 많은 꽃이 달려요.",
  },
  {
    plantName: "부채갯메꽃",
    scientificName: "Ipomoea pes-caprae Sweet",
    familyName: "메꽃과 Convolvulaceae",
    nameOrigin: "",
    plantingLocation: "미보유",
    distribution: "제주도",
    floweringPeriod: "여름",
    height: "",
    leafCharacteristics: "잎은 신심형으로 길이가 약 3-8cm정도이고 폭은 약 4-10cm정도이며 두껍고 요두이다.",
    bloomingSeason: "7",
    bloomingDetails: "포는 일찍 떨어지며 꽃받침은 막질이다. 화관은 지름이 약 5-6cm정도이며 홍자색을 띠고 있다.",
    stemCharacteristics: "줄기는 길게 땅위를 긴다.",
    hardiness: "",
    utilization: "",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200001541.01-91.jpg",
    description: "잎은 신심형으로 길이 3-8cm, 폭 4-10cm 정도이며 두꺼워요. 홍자색 꽃이 피고, 줄기는 땅을 길게 기어요.",
  },
  {
    plantName: "사옥",
    scientificName: "Prunus serrulata var. quelpaertensis Uyeki",
    familyName: "장미과 Rosaceae",
    nameOrigin: "",
    plantingLocation: "교목원",
    distribution: "제주도",
    floweringPeriod: "봄",
    height: "15m",
    leafCharacteristics:
      "잎은 호생하고 난형 또는 난상 피침형이다. 길이 6-12cm이고 양면에 털이 없다. 엽병은 길이 2-3cm이고 잎자루에 털이 있다.",
    bloomingSeason: "4",
    bloomingDetails: "담홍색 또는 거의 백색으로 꽃자루에 잔털이 있다. 꽃자루의 길이가 2-3cm이다.",
    stemCharacteristics: "수피는 옆으로 벗겨지며 암자갈색이다. 소지에 털이 없다.",
    hardiness: "",
    utilization: "관상용",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200001007.02-51.jpg",
    description: "잎은 호생하고 난형으로 6-12cm예요. 담홍색 또는 백색 꽃이 피고, 꽃자루에 잔털이 있어요.",
  },
  {
    plantName: "석장",
    scientificName: "Burmannia cryptopetala Makino",
    familyName: "석장과 Burmanniaceae",
    nameOrigin: "",
    plantingLocation: "",
    distribution: "제주도",
    floweringPeriod: "가을",
    height: "5-12cm",
    leafCharacteristics: "비늘모양의 잎은 피침형 또는 좁은 난형이고 길이 3-4mm이며 끝이 뾰족하다.",
    bloomingSeason: "9",
    bloomingDetails:
      "화서는 단순하거나 1회 갈라진 산형화서로 1-5송이의 꽃이 밀생한다. 포는 잎과 같은 모양이다. 꽃은 직립하고 길이 8-10mm로 흰색이다. 상부는 황색이고 꽃자루는 짧으며 날개가 있다. 바깥쪽의 화피 열편은 난형이고 끝이 뾰족하며 길이 1.5-2mm, 안쪽의 화피 열편은 없다.",
    stemCharacteristics: "전체가 백색이고 직립하며 줄기는 대개 단순하다.",
    hardiness: "",
    utilization: "관상용",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200000799.02-51.jpg",
    description:
      "비늘모양 잎은 피침형이며 3-4mm예요. 흰색 꽃이 피고, 화서는 단순하거나 갈라져요. 줄기는 백색이고 직립해요.",
  },
  {
    plantName: "섬바위장대",
    scientificName: "Arabis serrata var. hallaisanensis (Nak.) Ohwi",
    familyName: "십자화과 Cruciferae",
    nameOrigin: "",
    plantingLocation: "초본원",
    distribution: "제주도",
    floweringPeriod: "여름",
    height: "10-20cm",
    leafCharacteristics:
      "* 근생엽: 총생하며 주걱모양으로 길이 5-30mm, 폭 2.5-7mm정도이며 불규칙하게 톱니가 있다. * 경생엽: 밑의 것이 피침형이며 불규칙한 톱니가 있다.",
    bloomingSeason: "6",
    bloomingDetails:
      "흰색의 꽃이 핀다. 총상화서이며 원줄기 끝에서 선다. 소화경은 길이 3-4mm정도이며 성모가 있으나 열매일 때는 길이 7-10mm정도가 되며 털이 없어진다. 꽃받침잎은 길이 3mm이며 꽃잎은 길이 6-7mm정도가 된다.",
    stemCharacteristics: "전체에 별 모양의 털과 차상의 털이 있다.",
    hardiness: "",
    utilization: "",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200000922.jpg",
    description: "주걱모양, 경생엽은 피침형이에요. 흰색 꽃이 피고, 전체에 별 모양의 털이 있어요.",
  },
  {
    plantName: "애기달맞이꽃",
    scientificName: "Oenothera laciniata Hill",
    familyName: "바늘꽃과 Onagraceae",
    nameOrigin: "근래에 도래한 유럽 원산인 식물. 달맞이꽃에 비해 아주 작아서 애기달맞이꽃이라고 한다.",
    plantingLocation: "양묘포지",
    distribution: "제주도",
    floweringPeriod: "봄",
    height: "20-50cm",
    leafCharacteristics:
      "* 근생엽: 자루가 길며 깃 모양 또는 파상으로 갈라진다. * 경생엽: 피침형 또는 긴 타원형이며, 약간 깃 모양으로 갈라진다.",
    bloomingSeason: "5",
    bloomingDetails:
      "꽃은 포엽 겨드랑이에 1송이씩 달리며, 꽃받침통은 길고, 꽃받침은 4장이다. 꽃은 밝은 노란색으로 지름 2cm 내외이며 꽃잎은 4장이고 자방은 원기둥 모양이며 암술대는 끝이 4갈래이다. 담황색에서 황적색으로 변한다.",
    stemCharacteristics: "줄기는 기고, 전체에 개출된 털이 있다.",
    hardiness: "",
    utilization: "",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200001416.01-72.jpg",
    description:
      "자루가 길고 깃 모양, 경생엽은 피침형이에요. 밝은 노란색 꽃이 피고, 줄기는 기며 전체에 개출된 털이 있어요.",
  },
  {
    plantName: "채진목",
    scientificName: "Amelanchier asiatica (S. et Z.) Endl.",
    familyName: "장미과 Rosaceae",
    nameOrigin: "",
    plantingLocation: "희귀특산수종원",
    distribution: "제주도",
    floweringPeriod: "봄",
    height: "5-10m",
    leafCharacteristics: "낙엽관목. 잎은 호생하는 난형으로 길이 4-8cm, 폭 2.5-4cm이며 가장자리에 가는 톱니가 있다.",
    bloomingSeason: "4",
    bloomingDetails:
      "꽃은 흰색으로 피고 총상화서이며 솜털이 많다. 꽃잎은 5장이고 선형으로 길이 10-15mm, 폭 2-3mm이며 원두이다. 꽃받침은 피침형으로 젖혀진다. 수술은 20개이고 꽃받침통보다 약간 길다. 암술대는 5갈래이고 자방에 털이 있다.",
    stemCharacteristics:
      "햇가지에 흰 솜털이 나지만 뒤에 떨어진다. 가지는 가늘고 길며 적갈색이 돌고 둥근 피목이 산생한다.",
    hardiness: "강함",
    utilization: "정원수",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200001026.jpg",
    description: "호생 난형으로 4-8cm, 가는 톱니가 있어요. 흰색 꽃이 피고 솜털이 많아요.",
  },
  {
    plantName: "백서향",
    scientificName: "Daphne kiusiana Miq.",
    familyName: "팥꽃나무과 Thymeleaceae",
    nameOrigin: "",
    plantingLocation: "관목원",
    distribution: "남부 지방",
    floweringPeriod: "겨울",
    height: "1m",
    leafCharacteristics:
      "상록관목. 잎은 호생하고 혁질이며 털이 없고 광택이 있다. 도피침형 예두이고 끝이 둔하며 길이가 2.5-8cm정도이고 폭은 1.2-3.5cm이다. 가장자리가 밋밋하고 밑부분은 점차 좁아져서 짧은 엽병과 연속된다.",
    bloomingSeason: "1",
    bloomingDetails:
      "개화기:2-3월. 꽃은 이가화로서 백색의 꽃이 전년지 끝에 모여 달린다. 포는 넓은 피침형이고, 화경은 길이가 2mm정도로서 백색의 잔털이 있다. 꽃받침통은 길이가 7-8mm이고 잔털이 있다. 열편은 4개이고 길이는 3mm정도이며 겉에 털이 있다. 자방은 난형이고 털이 있으며 암술대에 털이 없고 암술머리는 두상이다.",
    stemCharacteristics: "",
    hardiness: "",
    utilization: "",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200001392.jpg",
    description: "백서향은 잎이 윤기 있고 털이 없는 호생 잎을 가져요. 흰 꽃이 펴요. 꽃받침통과 화경에 잔털이 있어요.",
  },
  {
    plantName: "동백나무",
    scientificName: "Camellia japonica L.",
    familyName: "차나무과 Theaceae",
    nameOrigin: "",
    plantingLocation: "교목원",
    distribution: "남부 지방, 울릉도, 대청도",
    floweringPeriod: "겨울",
    height: "7m",
    leafCharacteristics:
      "상록소교목. 잎은 호생한다. 가죽질의 긴 타원형으로 표면은 짙은 녹색에 윤기가 나고 가장자리에 물결 모양의 톱니가 있으며, 뒷면은 황록색이다. 길이가 5-12cm 가량이고 폭은 3-7cm정도 된다. 엽병은 길이가 2-15mm로 털이 없다.",
    bloomingSeason: "12",
    bloomingDetails:
      "개화기:2-4월. 붉은색의 꽃이 1송이씩 가지 끝에 붙으며 꽃자루가 없다. 작은 포는 여러 장으로 둥근 모양이며 겉에 흰 털이 있다. 꽃받침 5장으로 길이가 서로 다르고, 난상 원형, 길이 1-2cm이다. 꽃잎은 5장으로 밑부분이 서로 붙고 다시 수술과 붙어 있다. 수술은 다수이고, 화사는 희고 서로 붙어 통수술을 이루며, 꽃밥은 노란색이다. 자방에는 털이 없고, 암술대는 3갈래이다.",
    stemCharacteristics: "기부에서 갈라져 관목상으로 되는 것이 많으며 수피는 회갈색이고 평활하며 소지는 갈색이다.",
    hardiness:
      "꽃의 형태, 색깔, 잎 등에 많은 변화가 있다. 꽃잎이 거의 수평으로 퍼지는 것을 뜰동백(var. <i>hortensis</i> Mak.), 흰 꽃이 피는 것을 흰동백(for. <i>albipetala</i> H. Chang), 어린 가지와 잎 뒷면 맥 위 및 씨방에 털이 있는 것을 애기동백(<i>C. sasanqua</i> Thunb.)이라고 한다.",
    utilization: "",
    imageUrl: "https://www.newsje.com/news/photo/201709/98896_110250_2032.jpg",
    description: "동백나무는 붉은 꽃이 가지 끝에 핀답니다. 꽃받침은 5장이고 꽃잎도 5장이에요.",
  },
  {
    plantName: "유채꽃",
    scientificName: "Brassica campestris subsp. napus var. nippo-oleifera Makino",
    familyName: "십자화과 Cruciferae",
    nameOrigin: "",
    plantingLocation: "기타원외",
    distribution: "남부 지방",
    floweringPeriod: "겨울",
    height: "1m",
    leafCharacteristics: "",
    bloomingSeason: "2",
    bloomingDetails: "",
    stemCharacteristics: "",
    hardiness: "",
    utilization: "",
    imageUrl:
      "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcS4oAGu7cxLdiMAildx0RNOQlzcWCOFSW4JId5R8blz4zXZo0CF_edVJQ-EkvQRrS52MyFczOGD0TwAvHU",
    description:
      "유채는 깃털 모양 잎과 톱니가 있어요. 4월에 노란 꽃이 피고, 수술 6개와 암술 1개가 있어요. 유채꽃의 꽃말은 '쾌활함'으로, 기분을 밝고 행복하게 만들어 줘요.",
  },
  {
    plantName: "수국",
    scientificName: "Hydrangea macrophylla (Thunb.) Ser.",
    familyName: "범의귀과 Saxifragaceae",
    nameOrigin: "",
    plantingLocation: "화목원",
    distribution: "중부 이남",
    floweringPeriod: "여름",
    height: "1m",
    leafCharacteristics: "",
    bloomingSeason: "8",
    bloomingDetails: "",
    stemCharacteristics: "",
    hardiness: "",
    utilization: "",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200009998.jpg",
    description:
      "수국은 넓은 난형 잎이며, 꽃은 6-10월에 피고 진한 자주색에서 붉은색으로 변해요. 대형 산방화서에 꽃받침이 4-5장 있고, 수술은 약 10개 정도예요. 수국은 변덕과, 변심에 가려진 ‘진실된 마음’이라는 꽃말도 가지고 있습니다.",
  },
  {
    plantName: "왕벚나무",
    scientificName: "Prunus yedoensis Matsum",
    familyName: "장미과 Rosaceae",
    nameOrigin: "",
    plantingLocation: "교목원",
    distribution: "제주도 한라산",
    floweringPeriod: "봄",
    height: "15m",
    leafCharacteristics:
      "낙엽교목. 잎은 호생하고 타원형 또는 난형이며 길이는 6-12cm가량 된다. 가장자리에 겹톱니가 있고 윗면에 털이 없으며 뒷면의 맥 위와 잎자루에는 털이 있다. 엽병 또는 잎의 밑부분에 밀선이 발달하였다.",
    bloomingSeason: "3",
    bloomingDetails:
      "개화기:4월. 꽃은 잎보다 먼저 피고 연분홍색 또는 흰색이며 5-6송이가 산방화서를 이룬다. 총포가 여러 개이고 화서 밑에 붙으며 꽃자루에는 포가 발달하지 않는다. 꽃잎은 타원형이고 암술대에 털이 있다.",
    stemCharacteristics: "",
    hardiness: "",
    utilization: "관상용",
    imageUrl: "https://image.fnnews.com/resource/media/image/2018/03/30/201803301136341708_l.jpg",
    description:
      "왕벚나무는 호생하는 잎과 분홍 또는 흰 꽃을 피워요. 4월에 개화하며 산방화서를 이루는데, 암술대에는 털이 있어요. 왕벚꽃의 꽃말은 '고귀'와 '청순'이에요. 왕벚나무는 한 그루만 심어도 풍성한 벚꽃을 즐길 수 있어, 부드러운 여인을 연상시킨다고 해요.",
  },
  {
    plantName: "갯고들빼기",
    scientificName: "Crepidiastrum lanceolatum (Houtt.) Nakai",
    familyName: "국화과 Compositae",
    nameOrigin: "",
    plantingLocation: "미보유",
    distribution: "거제도",
    floweringPeriod: "가을",
    height: "20cm",
    leafCharacteristics: "",
    bloomingSeason: "11",
    bloomingDetails:
      "개화기:10-11월. 황색으로 피고 두화는 원줄기와 가지 끝에 산방상으로 달리며 밑부분에 잎같은 포엽이 있다. 화경은 길이가 3-9mm이다. 총포는 털이 없고 통형으로 길이 6-9mm, 폭 3-5mm이다. 밑부분에 포편이 있고 외편은 보다 짧으며 1맥이고 털이 다소 있으며 내편은 7-8개이다. 소화는 8-12개이고 화관은 길이 9-10mm이다.",
    stemCharacteristics: "",
    hardiness: "",
    utilization: "",
    imageUrl: "https://www.jeju.go.kr/files/sumok/ecology/0200001748.jpg",
    description:
      "갯고들빼기는 바닷가 바위틈에서 자란다. 줄기는 짧고 나무질이며, 잎은 주걱 모양이거나 타원형이야. 10~11월에 노란 꽃이 피는데, 열매에는 작은 부리가 있어. 관상식물로도 인기가 있습니다.",
  },
];
